apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-on-k8s2
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "demo/spark-on-k8s:latest"
  imagePullPolicy: Never
  mainClass: k8s.Demo
  mainApplicationFile: "local:///opt/spark/jars/spark-on-k8s-assembly-3.1.2.jar"
  sparkVersion: "3.1.2"
  restartPolicy:
    type: Never
#  volumes:
#    - name: "test-volume"
#      hostPath:
#        path: "/tmp"
#        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.2
    serviceAccount: spark
#    volumeMounts:
#      - name: "test-volume"
#        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.2
#    volumeMounts:
#      - name: "test-volume"
#        mountPath: "/tmp"